server {
  listen 80;
  server_name _;

  client_max_body_size 20m;

  location = / {
    return 302 /app/;
  }

  location = /app {
    return 301 /app/;
  }

  location /app/ {
    proxy_pass http://saleor-dashboard:80;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /dashboard/ {
    proxy_pass http://saleor-dashboard:80;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location = /graphql {
    return 301 /graphql/;
  }

  location /graphql/ {
    proxy_pass http://saleor-api:8000/graphql/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /media/ {
    proxy_pass http://saleor-api:8000/media/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /thumbnail/ {
    proxy_pass http://saleor-api:8000/thumbnail/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /static/ {
    proxy_pass http://saleor-api:8000/static/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
